### ISSUE TITLE
question: define code blocks in proto?

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#109] opened 2020-06-19 12:45 UTC
With the recent move to protobuf many of the types are represented in protobuf. Should we remove the reliance of representing types in the spec repository in go and move towards proto as it is language-agnostic?

**Comment by erikgrinaker** [comment] 2020-06-19 12:49
Duplicate of #89.

**Comment by marbar3778** [comment] 2020-06-19 12:49
ah whoops thanks

**Closed by erikgrinaker** 2020-06-19 12:49 UTC
